name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_DEFAULT_REGION: 'ap-southeast-2'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

  PullRequestBuild:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v2
      - name: CDK Diff
        if: github.event_name == 'pull_request'
        run: npm run cdk:diff
        working-directory: ./cdk

      - name: Unit Test
        if: github.event_name == 'pull_request'
        run: gradle test

  Deployment:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v2
      - name: CDK Deploy
        if: github.event_name == 'push'
        run: npm run cdk:deploy
        working-directory: ./cdk
